# Atividade Prática

**Módulo**: Metaheurísticas Bioinspiradas e Tomada de Decisão Inteligente 

**Atividade**: Atividade 1 - Busca e Otimização

**Professor**: Diego Pinheiro, PhD

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append("..")

In [3]:
from metaheuristics import *

In [7]:
initial_state_grid = np.array([
    [None, 1,  3],
    [4, 2, 6],
    [7, 5, 8]
])

initial_state = State(grid = initial_state_grid)

initial_state = Node(state=initial_state,parent=None,action=None, path_cost=0)
problem = Problem(initial_state)
node = best_first_search(problem)

In [8]:
print(node.path_cost)

4


In [9]:
print(node)

[[1 2 3]
 [4 5 6]
 [7 8 None]]

[[1 2 3]
 [4 5 6]
 [7 None 8]]

[[1 2 3]
 [4 None 6]
 [7 5 8]]

[[1 None 3]
 [4 2 6]
 [7 5 8]]

[[None 1 3]
 [4 2 6]
 [7 5 8]]

None
