# Atividade Prática

**Módulo**: Metaheurísticas Bioinspiradas e Tomada de Decisão Inteligente 

**Atividade**: Atividade 1 - Busca e Otimização

**Professor**: Diego Pinheiro, PhD

In [ ]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append("..")

In [5]:
from metaheuristics import *

## Sliding Tile Search

In [7]:
initial_state_grid = np.array([
    [None, 1,  3],
    [4, 2, 6],
    [7, 5, 8]
])

initial_state = SlidingTileState(
    board=grid_to_tuple(initial_state_grid)
)

print(initial_state)


SlidingTileState(board=(0, 1, 3, 4, 2, 6, 7, 5, 8))


In [9]:
initial_node = Node(state=initial_state,parent=None,action=None, path_cost=0)
problem = Problem(initial_state=initial_node)
node = best_first_search(problem)

ValueError: Calling nonzero on 0d arrays is not allowed. Use np.atleast_1d(scalar).nonzero() instead. If the context of this error is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.

In [8]:
print(node.path_cost)

4


In [9]:
print(node)

[[1 2 3]
 [4 5 6]
 [7 8 None]]

[[1 2 3]
 [4 5 6]
 [7 None 8]]

[[1 2 3]
 [4 None 6]
 [7 5 8]]

[[1 None 3]
 [4 2 6]
 [7 5 8]]

[[None 1 3]
 [4 2 6]
 [7 5 8]]

None


In [10]:
print(node.state)

[[1 2 3]
 [4 5 6]
 [7 8 None]]


In [11]:
print(node.parent)

[[1 2 3]
 [4 5 6]
 [7 None 8]]

[[1 2 3]
 [4 None 6]
 [7 5 8]]

[[1 None 3]
 [4 2 6]
 [7 5 8]]

[[None 1 3]
 [4 2 6]
 [7 5 8]]

None


In [ ]:
print(node.parent.state)

[[1 2 3]
 [4 5 6]
 [7 None 8]]
